# Generated by Django 5.2.6 on 2025-09-24 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='3-letter IATA airport code', max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=10)),
                ('distance_km', models.IntegerField(help_text='Distance in kilometers')),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes')),
                ('end_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='aiport.airport')),
                ('start_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='aiport.airport')),
            ],
        ),
    ]
